### PR TITLE
[BUGFIX] no pointer in type case in component

### PR DESCRIPTION
**Pull request by genofire**
Does somebody tests the component example ?

### CODE REVIEW

**Comment by mremond** [comment]
Yes, I tried it and tried it again and I did not not had any issue.
What's your issue ?

I tried your patch and the component crashes for me with that change.

**Comment by genofire** [comment]
It throws the error:
 `unexpected packet, got component:handshake`

**Comment by mremond** [comment]
Yes, you are right. The component connects and works fine but does return an error despite the success.
The example client did not check the error returned. I fixed the example to handle the error and will merge your patch.

Thanks!

**Comment by genofire** [comment]
https://dev.sum7.eu/genofire/thrempp

It works already by sending and recieveing Threema TextMessages -> thank you for this library :+1:

**Comment by mremond** [comment]
@genofire Thanks for sharing this 😄 Glad to know it is useful.

**Pull request merged**
