### PR TITLE
Introduce Transport interface and add Websocket support

### PR DESCRIPTION
**Pull request by wichert**
This PR aims to introduce the groundwork to support multiple transports, including the websocket transport requested in  #112. I used a basic approach: introduce a new `Transport` interface which handles network connection and reading/writing tasks. There are also some obvious flaws:

* [ ] I have not tested this beyond checking that the tests still pass
* [x] There is no way to select the transport to use at the moment
* [x] There should be a second transport implementation to show that this is useful.
* [x] Handling of StartTLS needs to be moved into the transport, using either an only-allow-secure-connect flag or a report-if-connection-is-secure method that the session can check.

 If you are happy with the approach I used here I'll expand this further and implement a WebSocket transport.

### CODE REVIEW

**Comment by wichert** [comment]
@mremond Would you have a chance to take a quick look at this today? I can spent a few hours on this tomorrow, but would like to have some feedback on the general design first.

**Comment by wichert** [comment]
There is a fair bit of code duplication between cert_checker.go and session.go at the moment. I can try to remove that by making ServerCheck use Session and Transport, but I want to postpone that to a separate PR after this one has been merged.

**Comment by mremond** [comment]
I have an error when trying to reuse existing test client:

```
2019/10/11 15:29:50 unrecoverable connect error : tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```

It seems the servername is not set properly.
However, it seems you still attempt to set it:
https://github.com/FluuxIO/go-xmpp/pull/119/files#diff-f636499bfb7997868676dcb97590fc99R39

There must be something lost somewhere in the flow, but I did not debug it yet.

**Comment by mremond** [comment]
I also tried to connect using Websocket, but it does not see to even attempt to reach my server.

Here is the test client I have been using: https://gist.github.com/mremond/34603a0999023362f12553d22bf4c623

**Comment by wichert** [comment]
I have gotten to doing some tests yet, so I’m not surprised it doesn’t quite work yet. I’ll continue working on this on Monday.

**Comment by wichert** [comment]
There were a few issues involved here:

* The XMPP transport was mixing up the TLS config on the Transport instance and the TransportConfiguration instance passed in.
* The WebSocket transport had an incorrect if condition.
* Both transports did not correctly return a ConError on connection errors.

**Comment by mremond** [comment]
Thanks!

I have scheduled some time to test it tomorrow morning.

**Comment by mremond** [comment]
Sorry I was sidetracked today, I hope to be able to check your PR tomorrow.

Thanks !

**Comment by mremond** [comment]
Hi, 

I see two issues for now:
1. Trying to connect with starttls on standard tcp port (5222) does not work. It seems the connection does not switch properly to TLS mode.
2. When trying to use websocket, the switch to websocket is ok but the stream open needs to be slightly different. For now client is sending standard <stream:stream ...>, but for websocket it should be:

```
  <open xmlns="urn:ietf:params:xml:ns:xmpp-framing"
             to="example.com"
             version="1.0" />
```

See: https://tools.ietf.org/html/rfc7395

There may also be some needs to tweak check the framing of packets inside a websocket frame. I expect so the framing part will be right.

**Comment by wichert** [comment]
FYI I am still working on this in between other things. The different opening statement for websockets an XMPP protocol required moving the responsibility to handle those into the transport, which did result in a nice cleanup. However keepalives are turning out to be a bit of a rabit hole due to how the websocket library handles control frames. I am very close to having that working now; hopefully I will have something to review tomorrow.

**Comment by wichert** [comment]
@mremond I think it's ready for another review now!

**Comment by mremond** [comment]
@wichert Thanks, I will have a look

**Comment by mremond** [comment]
Currently testing it with TLS on xmpp_echo example. It seems the client does nothing anymore after proceed.
I also could not connect with Websocket. It seems it is stuck trying to send the open packet.
I will try to have a look to see if I can understand what is happening when I get some time.

**Comment by wichert** [comment]
I'm puzzled why you get different results than I do. For what it's worth this is the output I get from an xmpp-echo run with a websocket:

```
❯ ./xmpp_echo
SEND:
<open xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="localhost" version="1.0" />

RECV:
<open xmlns='urn:ietf:params:xml:ns:xmpp-framing' version='1.0' xml:lang='en' id='12001456799841970371' from='localhost'/>

RECV:
<stream:features xmlns:stream='http://etherx.jabber.org/streams'><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='JhapnK81ccSY5SDbH2S875G5mp0='/><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>DIGEST-MD5</mechanism><mechanism>X-OAUTH2</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms></stream:features>

SEND:
<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>ADRoOXJkMnlkM3Q1OGZid3hlMjU3cnZqZDYAUzd5WkJzREllN2JvaTZydVZoaGlvR0h6TTZZVzZ2Ym9Nbm1sZ3VTNUJVVT0=</auth>

RECV:
<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>
```

I do see with starttls fails. The current flow looks like this:

1. `Client.Resume` connects the transport
1. `Client.Resume calls `NewSession` to create a new session
1. `NewSession` creates a `Session` instance and calls `Session.init`
1. `Session.init` calls `Session.open`
1. `Session.open` parses the `<stream:features>` element
1. `NewSession` calls `Session.startTlsIfSupported`
1. `Session.startTlsIfSupported` handles StartTLS
1. `NewSession` calls `Session.reset` if StartTLS succeeded
1. `Session.reset` calls `Session.open`, which tries to read a `<stream:features>` element.

The last step will obviously fail, since after StartTLS you must proceed to authentication. At that point the client will wait for an element the server is not sending, until the server times out waiting for auth and closes the stream.

I don't think I really changed the flow there, so I'm a bit puzzled as to why this used to work.

**Comment by wichert** [comment]
I see what I'm missing: start StartTLS you have to initiate a new stream, which I wasn't doing. That should be pretty easy to fix up.

**Comment by wichert** [comment]
@mremond I'm guessing it shows that I am new to XMPP.. I've fixed the code to correctly start a new stream after StartTLS and authentication. This seems to make everything a lot happier.

**Comment by mremond** [comment]
Thanks for the new patch!
It fixed the SSL issue with the standard TCP/IP transport.

There is still on minor hiccup with the websocket part. When configured with (not allowing insecure):

```
	config := xmpp.Config{
		TransportConfiguration: xmpp.TransportConfiguration{
			Address: "wss://localhost:5443/ws",
		},
		Jid:          "test@localhost",
		Credential:   xmpp.Password("test"),
		StreamLogger: os.Stdout,
		//Insecure:     true,
	}
```

It stops the negociation with: 

```
2019/10/28 14:31:10 unrecoverable connect error : Transport does not support starttls
```

It seems we need a way to let the transport know the connection is already using TLS, maybe throught the same hook that fail.

I will try to have a look so that we can finish that feature and release it :)

Anyway, many many thanks for all your effort put into this feature. I am really enjoying being able to work with you on this feature :)

**Comment by wichert** [comment]
The transport already knows if the connection is secure, and exposes that via the `IsSecure()` method. I've just pushed a small tweak which skips `startTlsIfSupported()` if the transport indicates the connection is already secure. That should fix the problem you were seeing.

It's been a pleasure to work on this! Once this PR has landed I intend to look at #120 and #78; I am going to need to a solution for both of those. It would be very helpful if you could provide some feedback on a design direction for those.

**Comment by mremond** [comment]
Thanks, I think we are good :)

**Pull request merged**
