### PR TITLE
Add CharacterData field to Node

### LINKED ISSUE #110: No way to add text context to an XML Node
We have an XMPP component that needs to send an IQ result with an XML element containing JSON. My code to do that looks like this:

```go
jsonData, err := json.Marshal(space)
if err != nil { … }

iqResp := stanza.NewIQ(stanza.Attrs{Type: "result", From: iq.To, To: iq.From, Id: iq.Id})
iqResp.Any = &stanza.Node{
	XMLName: xml.Name{Space: NSCryphoProtocol, Local: "space"},
	Content: string(jsonData),
}
if err := s.Send(iqResp); err != nil {
	m.errorLog.Printf("Error sending ping response: %v", err)
}
```

This does not work: the generated space element has no content

```xml
<iq type="result" id="id" from="target@domain" to="sender@domain">
  <space xmlns="http://crypho.com/ns/crypho"></space>
</iq>
```

I suspect that the best way to handle this is to add a new `CharData` field to `Node`:

```go
type Node struct {
        XMLName xml.Name
        Attrs   []xml.Attr `xml:"-"`
        Content string     `xml:",innerxml"`
        Nodes   []Node     `xml:",any"`
        CharData string `xml:",chardata"`
}
```

And process that in `MarshalXml`.

### PR DESCRIPTION
**Pull request by wichert**
This allows including character data in nodes. fixes #110

### CODE REVIEW

**Comment by wichert** [comment]
@mremond Does this look ok?

**Comment by mremond** [comment]
Sorry, I did not had time to test, but I guess the best approach is probably to try getting everything into content. It is not clear to me why we would have two fields (and then what the content fields would be used for).

**Comment by wichert** [comment]
Unfortunately it seems that Content is never marshalled. If I rewrite the test to do use Content like so:

```go
	node := stanza.Node{
		XMLName: xml.Name{Space: "go-xmpp", Local: "data"},
		Content: "character data",
	}

	xmlData, err := xml.Marshal(node)
	if err != nil {
		t.Error("Can not marshal Node with character data")
		return
	}

	if !strings.Contains(string(xmlData), "character data") {
		t.Errorf("Character data not output: %v", string(xmlData))
		return
	}
```

The test fails:

```
--- FAIL: TestNodeMarshalling (0.00s)
    node_test.go:24: Character data not output: <data xmlns="go-xmpp"></data>
```

This is surprising since [the documentation claims otherwise](https://golang.org/pkg/encoding/xml/#Marshal):

> - a field with tag ",innerxml" is written verbatim, not subject  to the usual marshaling procedure.

**Comment by wichert** [comment]
I just realised it isn't surprising, since there is a MarshalXML method that just doesn't look at it.

Thinking about it a bit more I'm not sure if it makes is desiable to output the `Content` field: it would break round-tripping. Currently you can Unmarshall and Marshall an XML fragment and get the exact same output, which feels like a nice quality to have. If you modify Marshal to include the Content field you would duplicate the contents of the Node if you try to do that.

**Comment by mremond** [comment]
Hello,
Thanks for the feedback. My point was  indeed to try making the code compliant with content to make it somewhat bidirectional and still work with XML and standard content. For example, maybe we just want to use content as cdata. I need to think why we would need to have both options.

**Comment by wichert** [comment]
@mremond Is there some way we can move this forward? Right now I'm a bit stuck since there is no way to insert an element with chardata in an IQ message without essentially duplicating the IQ type - something I would prefer not to have to do.

**Comment by wichert** [comment]
I did find a workaround:

```go
type textPayload struct {
	XMLName xml.Name
	Content string `xml:",cdata"`
}

func (r textPayload) Namespace() string {
	return r.XMLName.Space
}

func Func() {
        …
	iqResp := stanza.NewIQ(stanza.Attrs{Type: "result", From: iq.To, To: iq.From, Id: iq.Id})
	iqResp.Payload = &textPayload{
		XMLName: xml.Name{Space: cryphoXmpp.NSCryphoProtocol, Local: "space"},
		Content: string(jsonSpace),
	}
}
```

**Comment by mremond** [comment]
Sorry, I have to work on other topics at the moment, but I will be back to this issue ASAP.

Thanks !

**Comment by mremond** [comment]
I do not think it is a workaround. It looks to me like the intended way to use the lib. You need to define your payload to properly marshal / unmarshal it.

**Comment by mremond** [comment]
For the record, as I said, I think the way to go is to model your stanza using custom payload. You can find more info here: 

That said, I think it was worth making Marshal / Unmarshal symmetric for the generic node. For that, we should indeed use cdata instead of innerxml. That was my point when saying we do not need to have to fields. I think making Content be a cdata field and marshalling it is enough.

So, it means that with current head, you should also be able to use the generic node (and content) directly, event if it is not the preferred way.

Thanks for raising this issue !

**Comment by wichert** [comment]
We expose a fairly large API over XMPP, so we have a lot of payload types that are only used in one place. Being able to use Node to construct those payloads means we don't need to create a lot of types that will never be used elsewhere, hence my interest in being able to use Node with chardata.

Thanks for the fix!

**Comment by mremond** [comment]
Well, the benefit of having payload defined, is that the structure is checked at compiled time. Even if there is quite some code, it can be worth it. Anyway, I think all is good now.

**Pull request closed without merging**
