### PR TITLE
Stanza package & pattern to help building stanzas

### PR DESCRIPTION
**Pull request by mremond**
- Move parsing and stanza marshalling / unmarshalling to stanza package
- Add pattern & basic helpers to simplify stanza building.
This was requested on #61

### CODE REVIEW

**Comment by genofire** [comment]
locks like import / get does not work with `gosrc.io/xmpp/stanza`:
```
package gosrc.io/xmpp/stanza: unrecognized import path "gosrc.io/xmpp/stanza" (parse https://gosrc.io/xmpp/stanza?go-get=1: no go-import meta tags ())
```

**Comment by mremond** [comment]
Yes, sorry, I need to add an html page on gosrc.io, but got interrupted. I will add it in a while.

**Comment by mremond** [comment]
I think it is fixed.
Is it now working fine for you as well ?

**Comment by genofire** [comment]
jep :+1:

**Pull request merged**
