### PR TITLE
add option to accept all TLS certificates: insecureSkipTlsVerify

### PR DESCRIPTION
**Pull request by jiyeyuran**

### CODE REVIEW

**Comment by jiyeyuran** [comment]
@p1bot Signed.

**Comment by jiyeyuran** [comment]
@p1bot Can you merge this PR so that it can work with localhost xmpp ?

**Comment by mremond** [comment]
I do not understand in which case this PR would be needed. There is already the insecure option. Here is an example:
https://github.com/FluuxIO/go-xmpp/blob/master/_examples/xmpp_echo/xmpp_echo.go#L22

And if you want to skip the check of host, I do not understand why you would need it if your server is properly configured.

**Comment by jiyeyuran** [comment]
In my case, XMPP server is using TLS with self-signed certificate so that I have to skip to verify hostname. `Insecure` can only works for plain tcp which is not supported by my XMPP.

**Comment by mremond** [comment]
If you have self-signed certificate, the most secure way to support them is to add your Root CA in the trusted certs for that certificate. It is the most secure in the sense that it means you trust that authority (which is the case) and there is no risk shipping a software with TLS check disabled.

Maybe that could work for you ?

**Comment by jiyeyuran** [comment]
Yes, that would works, but there is not necessary to do this extra work in localhost environment. Maybe it is not need to add `InsecureSkipVerify` field in config. It would be nice to add this check:
```
		if !stanza.DefaultTlsConfig.InsecureSkipVerify {
			// We check that cert matches hostname
			s.err = tlsConn.VerifyHostname(domain)
		}
```

**Comment by jiyeyuran** [comment]
I have used this [xmpp library](https://github.com/mattn/go-xmpp). It supports the `InsecureSkipVerify` option.
[example.go](https://github.com/mattn/go-xmpp/blob/6093f50721ed2204a87a81109ca5a466a5bec6c1/_example/example.go#L45)

**Comment by mremond** [comment]
Yes, let me try to find a way. I would like to be sure it is not too easy to write an insecure client.

**Comment by mremond** [comment]
I implemented support for skipping TLS verification in that commit:
https://github.com/FluuxIO/go-xmpp/commit/9577036327f673190009f287802129a7ec904e7f

I have done it be allowing to pass and override `tls.Config`, so that we do not need a new options. It is better to rely on Go standard mechanisms.

**Comment by jiyeyuran** [comment]
Great work, finally, I don't need to modify the session.go and run `go build -mod=vendor`.

**Pull request closed without merging**
