### PR TITLE
Make keepalive interval configurable

### LINKED ISSUE #133: Make keepalive configurable
I have a bit of an unfortunate situation. We use ejabberd 16 (we can't upgrade due to processone/ejabberd#3025 until we remove our use of vcards), but that version does not implement websocket ping correctly. The websocket library sends a ping with a payload, and checks the payload for the received pong to check which ping request to mark as successful. A tcpdump shows the payload in the ping:

image

But the pong has no data:

image

This results in the websocket library discarding the pong, which causes the client to always fail its keepalive test and resetting the connection every 30 seconds.

To make the impact of that less manually I see a couple of solutions:

1. upgrade to a newer ejabberd (assuming this bug has been fix). Unfortunately this will likely require a few months of work and waiting for clients to be updated on our end.
1. add an option to disable keepalive completely. Since keepalives are valuable I'm not entirely in favour of this approach.
1. make keepalives smarter by resetting the keepalive timer if we receive any data. This will only help during busy time periods, so isn't optimal
1. make the keepalive timeout configurable, and for our specific situations just set it to an insanely long value..

### PR DESCRIPTION
**Pull request by wichert**
This fixes #133

### CODE REVIEW

**Comment by wichert** [comment]
FWIW I can't reproduce the test failure locally. Is that a heisenbug?

**Comment by remicorniere** [comment]
I have the same problem on my latest PR. 
I think it's a concurrency issue, and I'll try to fix the tests. I'll message you here once I get it fixed.

**Comment by wichert** [comment]
@mremond @remicorniere Can this be merged?

**Comment by remicorniere** [comment]
Yes !

**Comment by remicorniere** [comment]
@wichert 
Regarding the test bug, I finally got it working. Basically Decoder "objects" were not used appropriately in the tests and mock server. Sometimes we would have two decoders open on a single TCP connection. When that happened, and since Decoder has internal buffering and silently discards invalid documents, we would lose part of messages between decoders and just discard the other parts in other decoders.
This would lead some tests to fail. 
It is fixed now with #135

**Comment by wichert** [comment]
That sounds like it was painful to debug!

**Pull request merged**
