### PR TITLE
Add support for initial Router for packet matching & delegation

### PR DESCRIPTION
**Pull request by mremond**
- Add basic support for Router to make it easier to get your code trigger when some packets are received.
- Add initial support for namespace delegation (XEP-0355) and priviledged entities (XEP-0356) and example component.
- Clean up un IQ structures.

### CODE REVIEW

**Comment by mremond** [comment]
@genofire Here is a big change in API for components. You can check the diff on the example to get an idea of the impact. The main goal was to be able to support XEP-0355 and XEP-0356.
I have also tagged previous version as v0.1.0 so that you can stay on that branch if you are not yet confortable with new API or have doubts about it.

To get an idea of where we should be heading: I think we still should make it easier to generate XMPP packets. I need to think about how to improve that.

**Comment by genofire** [comment]
Is there a method to receive unrouted elements ?
i like to have a log message for it

**Comment by mremond** [comment]
@genofire No, there is no such method yet, but that's a good idea. It is possible that adding an empty route at the end would work, but I will create a ticket for that and expose a route function in API to clarify intent. We should add it.

**Comment by genofire** [comment]
And a route for IQ, `get` only.
(And maybe a SendIQ with callback func as parameter)

**Comment by genofire** [comment]
You should also handle unrouted iq with an error, like here:
https://github.com/FluuxIO/go-xmpp/blob/f7b7482d2e1aa7eec5127a47319db000e975437e/_examples/xmpp_component/xmpp_component.go#L53-L60

**Comment by genofire** [comment]
Which has a higher prio

```go
router.HandleFunc("iq", HandleMessage)
```
or
```go
router.NewRoute().IQNamespaces("urn:xmpp:delegation:1").HandlerFunc(HandleDelegation)
```
???

**Comment by mremond** [comment]
@genofire Thanks, I will add all this after I have closed by branch to improve packet building.
I have a tentative API here: #61

**Pull request merged**
