### PR TITLE
muc history of zero stanzes are not supported

### PR DESCRIPTION
**Pull request by genofire**
if `int` is `0` it will not be decoded - because you set `omitempty`.
Solution is to set use pointer so that `omitempty` would handle the pointer and not the value.
On this value a value like `0` is allowed.

---

if you do not use it like here programmed, please create tests for it.

### CODE REVIEW

**Comment by mremond** [comment]
Thanks for pointing this.
The thing is that use of pointer in that case only may be confusing.
Maybe we could just have a custom marshaller for a custom type that wrap int? Something like NullableInt. This is done in some DB drivers for example.

**Comment by genofire** [comment]
Of course, but this time with tests, that we really get the xml stanze we want ;)

(Not only unmarshaling)

**Comment by genofire** [comment]
Do we want merge it - better a unbeatiful master then a broken master.

You could create a issue for it, to make it later beautiful.

**Comment by mremond** [comment]
Hum, strange, let me see, I thought it was already merged, as I should have commited in the PR, but I do not see my commit.

**Comment by mremond** [comment]
I thought I had written that code, but I got confused with another code.
I latest commit, I adapted your test and introduced custom Marshaller / Unmarshaller.

You can know set NullableInt as follow:
```go
xmpp.History{MaxStanzas: xmpp.NewNullableInt(maxstanzas)}
```

You can check it as follow:

```go
if val, isSet := muc.History.MaxStanzas.Get(); isSet  {
    // The value is meaningful. If we find in val, we know it was deliberately set.
}
```

**Pull request merged**
