### PR TITLE
Setup GitHub actions to run tests

### PR DESCRIPTION
**Pull request by wichert**
I noticed you had to fix a failing test after my last PR, which is something I should have noticed myself. To help with that this PR adds a GitHub Action to automatically run all tests.

To enable this you need to [signup for GitHub Actions](https://github.com/features/actions/signup) for the FluuxIO organisation first. After that I should work automatically.

### CODE REVIEW

**Comment by mremond** [comment]
Thanks, let me have a look, I think that Codeship allow testing all branches. It is probably just a matter of enabling a setting there.

**Comment by wichert** [comment]
I haven't used Codeship myself, but I would expect any decent CI service to be able to test all branches and PRs. I'm also happy to provide a setup for CircleCI or Azure Devops as well if you prefer either of those. 

For reference [this is an example](https://github.com/wichert/k8s-sentry/actions) of what the output looks like.

**Comment by mremond** [comment]
I have enabled Codeship to access Pull request. It had somewhat lost the right to do so.

Let's see if this helps.

**Comment by mremond** [comment]
Codeship does not seem to trigger on latest PR. I think we should give Github Actions a try.

We will work on integrating your proposal. For our own record, what we need is:
- Reuse the -race flag to test against race conditions (see: https://github.com/FluuxIO/go-xmpp/blob/master/test.sh)
- Make sure we generate the test coverage (see: https://github.com/FluuxIO/go-xmpp/blob/master/test.sh)
- Use Codecov action to upload coverage result to codecov (See: https://github.com/codecov/codecov-action). I did not yet check how to encrypt the secret, but it would have to be encrypted.

**Comment by wichert** [comment]
I've been meaning to submit a known bad PR to test that, but I've been too occupied with other bits of our stack recently. If you want I can look at extending this PR.

**Comment by mremond** [comment]
@wichert We are willing to take over from there as for code coverage, it needs integration with our account. This will also help us get started with Github action.

Thanks for the idea and the quickstart :)
We will finish the integration, as it will be easier as we have all the required rights 👍

**Pull request merged**
